### ISSUE TITLE
python-libinput on PyPI not updated.

### ISSUE THREAD

**Issue by Py-GNU-Unix** [OzymandiasTheGreat/python-libinput#18] opened 2021-03-27 09:19 UTC
python-libinput 2.0 has been released, but on [PyPI](https://pypi.org/project/python-libinput/), it hasn't been updated since version 1.0. Can you update it? 

PS: good job. That's a very good library.

**Comment by somini** [comment] 2021-05-01 18:07
Duplicate of #13

**Closed** 2021-05-02 16:46 UTC

**Comment by somini** [comment] 2021-05-06 14:12
Just a heads up, this was closed because the project is looking for maintainers, not because it's fixed.
